package br.com.saboia.app.quote.to;

import java.util.List;


public class QuoteItemTO {
	
	private long id;
	
	private long idTaxQuoteItem;
	
	private long idTaxQuoteItemOriginal;
	
	private long idTaxQuote;
	
	private long idAdmMaterial;
	
	private long idAdmOrigin;
	
	private long idAdmOriginHW;
	
	private long idAdmOriginMT;
	
	private long idAdmOriginSW;
	
	private long idAdmOriginSV;
	
	private long idAdmDestination;
	
	private long idAdmMaterialClass;
	
	private long idAdmMaterialClassOriginal;
	
	private long idAdmMaterialClassPai;
	
	private long idAdmProductType;
	
	private long idAdmDiscClass;
	
	private int fLMType;
	
	private int fAvailable;
	
	private int fUseMaxIvaMaterialImportado;
	
	private int fAvailableMaterial;
	
	private int fSubstituicaoTributariaSaida;
	
	private int fSubstituicaoTributariaEntrada;
	
	private int fSubstituicaoTributariaSaidaMaterialClass;
	
	private int fSubstituicaoTributariaEntradaMaterialClass;

	private int fISSEspecial;
	
	private int fStandardISSRule;
	
	private int fStandardISSRuleSW;
	
	private int fVariacaoPartNumber;
	
	private int fAvailableMaterialClass;
	
	private int fISSEspecialMaterialClass;
	
	private int fReadOnly;
	
	private int fReadOnlyLine;
	
	private int fForceImporting;
	
	private int fDestinationWithProtocol;
	
	private int fTipoCalculo;
	
	private int fQuote;
	
	private int fReady;
	
	private int fItemPai;
	
	private int fItemPaiManual;
	
	private int fAutoGeneratedBySystem;
	
	private int fRackIsMissing;
	
	private int fZeroTaxMarket;
	
	private int fOrigemDaMercadoria;
	
	private int fMercadoriaImportada;
	
	private String sGroupNumber;
	
	private int iTaxModel;
	
	private int iLineNumber;
	
	private int iFlagTypeLine;
	
	private String sOrdem;
	
	private int iRowCount;
	
	private String sLabelProductTypePT;
	
	private String sLabelProductType;
	
	private String sCode;
	
	private String sNCMMaterialClass;
	
	private String sNCMMaterialClassPai;
	
	private String sNCM;
	
	private String sNCMOriginal;
	
	private String sModelMaterial;
	
	private String sModel;
	
	private String sDescriptionMaterial;
	
	private String sDescription;
	
	private String sImpDescription;
	
	private String sCommentsOtherCost;
	
	private int rQty;
	
	private double mDollarRate;
	
	private double mDealPrice;
	
	private double mImportedListPrice;
	
	private double mImportedCost;
	
	private double mTotalCost;
	
	private double mImportedDealPrice;
	
	private double mCostMaterialMaterial;
	
	private double mCostMaterial;
	
	private double mAdditionalCostValueDollar;
	
	private double mAdditionalCostFreight;
	
	private double mAdditionalCostProject;
	
	private double mAdditionalCostTraining;
	
	private double mAdditionalCostOtherCost;
	
	private double mDollarRateAdditionalCost;
	
	private double mCostCalculated;
	
	private double mSuggestedMargin;
	
	private double mUnitSuggestedNetPrice;
	
	private double mSuggestedNetPrice;
	
	private double mNetPrice;
	
	private double mUnitNetPrice;
	
	private double mFatorEntrada;
	
	private double mFatorCustoST;
	
	private double mNetPriceBaseDeCalculo;
	
	private double mUnitNetPriceBaseDeCalculo;
	
	private float rSuggestedMargin;
	
	private float netMargin;
	
	private float rDiscClassDiscount;
	
	private float rDiscount;
	
	private float rFatorSaida;
	
	private float rFatorDisconto;
	
	private float rICMSEstadoOrigemOrigin;
	
	private float rICMSInternoOrigemOrigin;
	
    private float rICMSInterEstadualOrigemOrigin;
	
	private float rICMSEstadoOrigemInternoMaterialClassOrigin;
	
	private float rICMSEstadoDestinoDestination;
	
	private float rICMSMAterialClass;
	
	private float rICMSMaterialClassMaterialClass;
	
	private float rICMSInterEstadualDestination;
	
	private float rICMSInterEstadualMaterialImportadoDestination;
	
	private float rIVAMaterialClassDestination;
	
	private float rIVAMaterialImportadoMaterialClassDestination;
	
	private float rICMSInternoMaterialClassDestination;
	
	private float rIPIMaterialClass;
	
	private float rPISProductType;
	
	private float rCOFINSProductType;
	
	private float rIRProductType;
	
	private float rCSSLProductType;
	
	private float rISSOrigin;
	
	private float rISSSoftOrigin;
	
	private float rISSOriginServ;
	
	private float rIVAOrigin;
	
	private float rIVAMaterialImportadoOrigin;
	
	private float rICMSEstadoOrigem;
	
	private float rICMSEstadoOrigemInterno;
	
	private float rICMSEstadoDestino;
	
	private float rICMSMaterialClass;
	
	private float rICMSInterEstadual;
	
	private float rICMSInterEstadualMaterialImportado;
	
	private float rIVA;
	
	private float rIVAMaterialImportado;
	
	private float rICMSInterno;
	
	private float rICMSRecuperar;
	
	private float rICMSProprioARecuperar;
	
	private float rICMSARecuperarST;
	
	private float rIPI;
	
	private float rIPIRecuperar;
	
	private float rPIS;
	
	private float rCOFINS;
	
	private float rIR;
	
	private float rCSSL;
	
	private float rISS;
	
	private double mUnitICMSEstadoOrigem;
	
	private double mUnitICMSEstadoOrigemInterno;
	
	private double mUnitICMSEstadoDestino;
	
	private double mUnitICMSMaterialClass;
	
	private double mUnitICMSInterEstadual;
	
	private double mUnitICMSInterEstadualMaterialImportado;
	
	private double mUnitICMSARecuperar;
	
	private double mUnitICMSARecuperarST;
	
	private double mUnitICMSProprioARecuperar;
	
	private double mUnitICMSST;
	
	private double mUnitIPI;
	
	private double mUnitIPIRecoverable;
	
	private double mUnitPIS;
	
	private double mUnitCofins;
	
	private double mUnitIR;
	
	private double mUnitCSSL;
	
	private double mUnitISS;
	
	private double mICMSEstadoOrigem;
	
	private double mICMSEstadoOrigemInterno;
	
	private double mICMSEstadoDestino;
	
	private double mICMSMaterialClass;
	
	private double mICMSInterEstadual;
	
	private double mICMSInterEstadualMaterialImportado;
	
	private double mICMSARecuperar;
	
	private double mICMSARecuperarST;

	private double mICMSProprioARecuperar;
	
	private double mICMSST;
	
	private double mIPI;
	
	private double mIPIReceber;
	
	private double mPIS;
	
	private double mCOFINS;
	
	private double mIR;
	
	private double mCSSL;
	
	private double mISS;
	
	private double mTaxesRecoverableMargin;
	
	private float rMarginItem;
	
	private double mTotalTaxes;
	
	private double mBaseCalculoST;
	
	private double mUnitGrossPrice;
	
	private double mGrossPrice;
	
	private double rGrossMargin;
	
	private int iCalculationModel;
	
	private String sCalculationMemoryMaterial;

	private String style;
	
	private String styleTd;
	
	private boolean checked;
	
	private List<SomaTotaisTO> listaTotais;
	
	public long getIdTaxQuoteItem() {
		return idTaxQuoteItem;
	}

	public void setIdTaxQuoteItem(long idTaxQuoteItem) {
		this.idTaxQuoteItem = idTaxQuoteItem;
	}

	public long getIdTaxQuote() {
		return idTaxQuote;
	}

	public void setIdTaxQuote(long idTaxQuote) {
		this.idTaxQuote = idTaxQuote;
	}

	public long getIdAdmMaterial() {
		return idAdmMaterial;
	}

	public void setIdAdmMaterial(long idAdmMaterial) {
		this.idAdmMaterial = idAdmMaterial;
	}

	public long getIdAdmOrigin() {
		return idAdmOrigin;
	}

	public void setIdAdmOrigin(long idAdmOrigin) {
		this.idAdmOrigin = idAdmOrigin;
	}

	public long getIdAdmOriginHW() {
		return idAdmOriginHW;
	}

	public void setIdAdmOriginHW(long idAdmOriginHW) {
		this.idAdmOriginHW = idAdmOriginHW;
	}

	public long getIdAdmOriginMT() {
		return idAdmOriginMT;
	}

	public void setIdAdmOriginMT(long idAdmOriginMT) {
		this.idAdmOriginMT = idAdmOriginMT;
	}

	public long getIdAdmOriginSW() {
		return idAdmOriginSW;
	}

	public void setIdAdmOriginSW(long idAdmOriginSW) {
		this.idAdmOriginSW = idAdmOriginSW;
	}

	public long getIdAdmOriginSV() {
		return idAdmOriginSV;
	}

	public void setIdAdmOriginSV(long idAdmOriginSV) {
		this.idAdmOriginSV = idAdmOriginSV;
	}

	public long getIdAdmDestination() {
		return idAdmDestination;
	}

	public void setIdAdmDestination(long idAdmDestination) {
		this.idAdmDestination = idAdmDestination;
	}

	public long getIdAdmMaterialClass() {
		return idAdmMaterialClass;
	}

	public void setIdAdmMaterialClass(long idAdmMaterialClass) {
		this.idAdmMaterialClass = idAdmMaterialClass;
	}
	
	public long getIdAdmMaterialClassPai() {
		return idAdmMaterialClassPai;
	}

	public void setIdAdmMaterialClassPai(long idAdmMaterialClassPai) {
		this.idAdmMaterialClassPai = idAdmMaterialClassPai;
	}

	public long getIdAdmProductType() {
		return idAdmProductType;
	}

	public void setIdAdmProductType(long idAdmProductType) {
		this.idAdmProductType = idAdmProductType;
	}

	public long getIdAdmDiscClass() {
		return idAdmDiscClass;
	}

	public void setIdAdmDiscClass(long idAdmDiscClass) {
		this.idAdmDiscClass = idAdmDiscClass;
	}

	public int getfLMType() {
		return fLMType;
	}

	public void setfLMType(int fLMType) {
		this.fLMType = fLMType;
	}

	public int getfAvailable() {
		return fAvailable;
	}

	public void setfAvailable(int fAvailable) {
		this.fAvailable = fAvailable;
	}

	public int getfSubstituicaoTributariaSaida() {
		return fSubstituicaoTributariaSaida;
	}

	public void setfSubstituicaoTributariaSaida(int fSubstituicaoTributariaSaida) {
		this.fSubstituicaoTributariaSaida = fSubstituicaoTributariaSaida;
	}

	public int getfSubstituicaoTributariaEntrada() {
		return fSubstituicaoTributariaEntrada;
	}

	public void setfSubstituicaoTributariaEntrada(int fSubstituicaoTributariaEntrada) {
		this.fSubstituicaoTributariaEntrada = fSubstituicaoTributariaEntrada;
	}

	public int getfSubstituicaoTributariaSaidaMaterialClass() {
		return fSubstituicaoTributariaSaidaMaterialClass;
	}

	public void setfSubstituicaoTributariaSaidaMaterialClass(
			int fSubstituicaoTributariaSaidaMaterialClass) {
		this.fSubstituicaoTributariaSaidaMaterialClass = fSubstituicaoTributariaSaidaMaterialClass;
	}

	public int getfSubstituicaoTributariaEntradaMaterialClass() {
		return fSubstituicaoTributariaEntradaMaterialClass;
	}

	public void setfSubstituicaoTributariaEntradaMaterialClass(
			int fSubstituicaoTributariaEntradaMaterialClass) {
		this.fSubstituicaoTributariaEntradaMaterialClass = fSubstituicaoTributariaEntradaMaterialClass;
	}

	public int getfISSEspecial() {
		return fISSEspecial;
	}

	public void setfISSEspecial(int fISSEspecial) {
		this.fISSEspecial = fISSEspecial;
	}

	public int getfStandardISSRule() {
		return fStandardISSRule;
	}

	public void setfStandardISSRule(int fStandardISSRule) {
		this.fStandardISSRule = fStandardISSRule;
	}

	public int getfStandardISSRuleSW() {
		return fStandardISSRuleSW;
	}

	public void setfStandardISSRuleSW(int fStandardISSRuleSW) {
		this.fStandardISSRuleSW = fStandardISSRuleSW;
	}

	public int getfAvailableMaterialClass() {
		return fAvailableMaterialClass;
	}

	public void setfAvailableMaterialClass(int fAvailableMaterialClass) {
		this.fAvailableMaterialClass = fAvailableMaterialClass;
	}

	public int getfISSEspecialMaterialClass() {
		return fISSEspecialMaterialClass;
	}

	public void setfISSEspecialMaterialClass(int fISSEspecialMaterialClass) {
		this.fISSEspecialMaterialClass = fISSEspecialMaterialClass;
	}

	public int getfReadOnly() {
		return fReadOnly;
	}

	public void setfReadOnly(int fReadOnly) {
		this.fReadOnly = fReadOnly;
	}

	public int getfReadOnlyLine() {
		return fReadOnlyLine;
	}

	public void setfReadOnlyLine(int fReadOnlyLine) {
		this.fReadOnlyLine = fReadOnlyLine;
	}

	public int getfForceImporting() {
		return fForceImporting;
	}

	public void setfForceImporting(int fForceImporting) {
		this.fForceImporting = fForceImporting;
	}

	public int getfDestinationWithProtocol() {
		return fDestinationWithProtocol;
	}

	public void setfDestinationWithProtocol(int fDestinationWithProtocol) {
		this.fDestinationWithProtocol = fDestinationWithProtocol;
	}

	public int getfTipoCalculo() {
		return fTipoCalculo;
	}

	public void setfTipoCalculo(int fTipoCalculo) {
		this.fTipoCalculo = fTipoCalculo;
	}

	public int getfQuote() {
		return fQuote;
	}

	public void setfQuote(int fQuote) {
		this.fQuote = fQuote;
	}

	public int getfReady() {
		return fReady;
	}

	public void setfReady(int fReady) {
		this.fReady = fReady;
	}

	public int getfItemPai() {
		return fItemPai;
	}

	public void setfItemPai(int fItemPai) {
		this.fItemPai = fItemPai;
	}

	public int getfRackIsMissing() {
		return fRackIsMissing;
	}

	public void setfRackIsMissing(int fRackIsMissing) {
		this.fRackIsMissing = fRackIsMissing;
	}

	public int getfZeroTaxMarket() {
		return fZeroTaxMarket;
	}

	public void setfZeroTaxMarket(int fZeroTaxMarket) {
		this.fZeroTaxMarket = fZeroTaxMarket;
	}

	public int getfOrigemDaMercadoria() {
		return fOrigemDaMercadoria;
	}

	public void setfOrigemDaMercadoria(int fOrigemDaMercadoria) {
		this.fOrigemDaMercadoria = fOrigemDaMercadoria;
	}

	public int getfMercadoriaImportada() {
		return fMercadoriaImportada;
	}

	public void setfMercadoriaImportada(int fMercadoriaImportada) {
		this.fMercadoriaImportada = fMercadoriaImportada;
	}

	public String getsGroupNumber() {
		return sGroupNumber;
	}

	public void setsGroupNumber(String sGroupNumber) {
		this.sGroupNumber = sGroupNumber;
	}

	public int getiTaxModel() {
		return iTaxModel;
	}

	public void setiTaxModel(int iTaxModel) {
		this.iTaxModel = iTaxModel;
	}

	public int getiLineNumber() {
		return iLineNumber;
	}

	public void setiLineNumber(int iLineNumber) {
		this.iLineNumber = iLineNumber;
	}

	public int getiFlagTypeLine() {
		return iFlagTypeLine;
	}

	public void setiFlagTypeLine(int iFlagTypeLine) {
		this.iFlagTypeLine = iFlagTypeLine;
	}

	public int getiRowCount() {
		return iRowCount;
	}

	public void setiRowCount(int iRowCount) {
		this.iRowCount = iRowCount;
	}

	public String getsLabelProductTypePT() {
		return sLabelProductTypePT;
	}

	public void setsLabelProductTypePT(String sLabelProductTypePT) {
		this.sLabelProductTypePT = sLabelProductTypePT;
	}

	public String getsLabelProductType() {
		
		if(sLabelProductType == null){
			sLabelProductType = getsLabelProductTypePT();
		}
		
		return sLabelProductType;
	}

	public void setsLabelProductType(String sLabelProductType) {
		this.sLabelProductType = sLabelProductType;
	}

	public String getsCode() {
		return sCode;
	}

	public void setsCode(String sCode) {
		this.sCode = sCode;
	}

	public String getsNCMMaterialClass() {
		return sNCMMaterialClass;
	}

	public void setsNCMMaterialClass(String sNCMMaterialClass) {
		this.sNCMMaterialClass = sNCMMaterialClass;
	}
			
	public String getsNCMMaterialClassPai() {
		return sNCMMaterialClassPai;
	}

	public void setsNCMMaterialClassPai(String sNCMMaterialClassPai) {
		this.sNCMMaterialClassPai = sNCMMaterialClassPai;
	}

	public String getsNCM() {
		return sNCM;
	}

	public void setsNCM(String sNCM) {
		this.sNCM = sNCM;
	}

	public String getsModelMaterial() {
		return sModelMaterial;
	}

	public void setsModelMaterial(String sModelMaterial) {
		this.sModelMaterial = sModelMaterial;
	}

	public String getsModel() {
		return sModel;
	}

	public void setsModel(String sModel) {
		this.sModel = sModel;
	}

	public String getsDescription() {
		return sDescription;
	}

	public void setsDescription(String sDescription) {
		this.sDescription = sDescription;
	}

	public String getsImpDescription() {
		return sImpDescription;
	}

	public void setsImpDescription(String sImpDescription) {
		this.sImpDescription = sImpDescription;
	}

	public int getrQty() {
		return rQty;
	}

	public void setrQty(int rQty) {
		this.rQty = rQty;
	}

	public double getmDollarRate() {
		return mDollarRate;
	}

	public void setmDollarRate(double mDollarRate) {
		this.mDollarRate = mDollarRate;
	}

	public double getmDealPrice() {
		return mDealPrice;
	}

	public void setmDealPrice(double mDealPrice) {
		this.mDealPrice = mDealPrice;
	}

	public double getmImportedListPrice() {
		return mImportedListPrice;
	}

	public void setmImportedListPrice(double mImportedListPrice) {
		this.mImportedListPrice = mImportedListPrice;
	}

	public double getmImportedCost() {
		return mImportedCost;
	}

	public void setmImportedCost(double mImportedCost) {
		this.mImportedCost = mImportedCost;
	}

	public double getmTotalCost() {
		return mTotalCost;
	}

	public void setmTotalCost(double mTotalCost) {
		this.mTotalCost = mTotalCost;
	}

	public double getmImportedDealPrice() {
		return mImportedDealPrice;
	}

	public void setmImportedDealPrice(double mImportedDealPrice) {
		this.mImportedDealPrice = mImportedDealPrice;
	}

	public double getmCostMaterialMaterial() {
		return mCostMaterialMaterial;
	}

	public void setmCostMaterialMaterial(double mCostMaterialMaterial) {
		this.mCostMaterialMaterial = mCostMaterialMaterial;
	}

	public double getmCostMaterial() {
		return mCostMaterial;
	}

	public void setmCostMaterial(double mCostMaterial) {
		this.mCostMaterial = mCostMaterial;
	}

	public double getmAdditionalCostValueDollar() {
		return mAdditionalCostValueDollar;
	}

	public void setmAdditionalCostValueDollar(double mAdditionalCostValueDollar) {
		this.mAdditionalCostValueDollar = mAdditionalCostValueDollar;
	}

	public double getmAdditionalCostFreight() {
		return mAdditionalCostFreight;
	}

	public void setmAdditionalCostFreight(double mAdditionalCostFreight) {
		this.mAdditionalCostFreight = mAdditionalCostFreight;
	}

	public double getmAdditionalCostProject() {
		return mAdditionalCostProject;
	}

	public void setmAdditionalCostProject(double mAdditionalCostProject) {
		this.mAdditionalCostProject = mAdditionalCostProject;
	}

	public double getmAdditionalCostTraining() {
		return mAdditionalCostTraining;
	}

	public void setmAdditionalCostTraining(double mAdditionalCostTraining) {
		this.mAdditionalCostTraining = mAdditionalCostTraining;
	}

	public double getmAdditionalCostOtherCost() {
		return mAdditionalCostOtherCost;
	}

	public void setmAdditionalCostOtherCost(double mAdditionalCostOtherCost) {
		this.mAdditionalCostOtherCost = mAdditionalCostOtherCost;
	}

	public double getmDollarRateAdditionalCost() {
		return mDollarRateAdditionalCost;
	}

	public void setmDollarRateAdditionalCost(double mDollarRateAdditionalCost) {
		this.mDollarRateAdditionalCost = mDollarRateAdditionalCost;
	}

	public double getmCostCalculated() {
		return mCostCalculated;
	}

	public void setmCostCalculated(double mCostCalculated) {
		this.mCostCalculated = mCostCalculated;
	}

	public double getmSuggestedMargin() {
		return mSuggestedMargin;
	}

	public void setmSuggestedMargin(double mSuggestedMargin) {
		this.mSuggestedMargin = mSuggestedMargin;
	}

	public double getmUnitSuggestedNetPrice() {
		return mUnitSuggestedNetPrice;
	}

	public void setmUnitSuggestedNetPrice(double mUnitSuggestedNetPrice) {
		this.mUnitSuggestedNetPrice = mUnitSuggestedNetPrice;
	}

	public double getmSuggestedNetPrice() {
		return mSuggestedNetPrice;
	}

	public void setmSuggestedNetPrice(double mSuggestedNetPrice) {
		this.mSuggestedNetPrice = mSuggestedNetPrice;
	}

	public double getmNetPrice() {
		return mNetPrice;
	}

	public void setmNetPrice(double mNetPrice) {
		this.mNetPrice = mNetPrice;
	}

	public double getmUnitNetPrice() {
		return mUnitNetPrice;
	}

	public void setmUnitNetPrice(double mUnitNetPrice) {
		this.mUnitNetPrice = mUnitNetPrice;
	}

	public double getmFatorEntrada() {
		return mFatorEntrada;
	}

	public void setmFatorEntrada(double mFatorEntrada) {
		this.mFatorEntrada = mFatorEntrada;
	}

	public double getmFatorCustoST() {
		return mFatorCustoST;
	}

	public void setmFatorCustoST(double mFatorCustoST) {
		this.mFatorCustoST = mFatorCustoST;
	}

	public double getmNetPriceBaseDeCalculo() {
		return mNetPriceBaseDeCalculo;
	}

	public void setmNetPriceBaseDeCalculo(double mNetPriceBaseDeCalculo) {
		this.mNetPriceBaseDeCalculo = mNetPriceBaseDeCalculo;
	}

	public double getmUnitNetPriceBaseDeCalculo() {
		return mUnitNetPriceBaseDeCalculo;
	}

	public void setmUnitNetPriceBaseDeCalculo(double mUnitNetPriceBaseDeCalculo) {
		this.mUnitNetPriceBaseDeCalculo = mUnitNetPriceBaseDeCalculo;
	}

	public float getrSuggestedMargin() {
		return rSuggestedMargin;
	}

	public void setrSuggestedMargin(float rSuggestedMargin) {
		this.rSuggestedMargin = rSuggestedMargin;
	}

	public float getrDiscClassDiscount() {
		return rDiscClassDiscount;
	}

	public void setrDiscClassDiscount(float rDiscClassDiscount) {
		this.rDiscClassDiscount = rDiscClassDiscount;
	}

	public float getrDiscount() {
		return (rDiscount * 100);
	}

	public void setrDiscount(float rDiscount) {
		this.rDiscount = (rDiscount / 100);
	}

	public float getrFatorSaida() {
		return rFatorSaida;
	}

	public void setrFatorSaida(float rFatorSaida) {
		this.rFatorSaida = rFatorSaida;
	}

	public float getrFatorDisconto() {
		return rFatorDisconto;
	}

	public void setrFatorDisconto(float rFatorDisconto) {
		this.rFatorDisconto = rFatorDisconto;
	}

	public float getrICMSEstadoOrigemOrigin() {
		return rICMSEstadoOrigemOrigin;
	}

	public void setrICMSEstadoOrigemOrigin(float rICMSEstadoOrigemOrigin) {
		this.rICMSEstadoOrigemOrigin = rICMSEstadoOrigemOrigin;
	}

	public float getrICMSInternoOrigemOrigin() {
		return rICMSInternoOrigemOrigin;
	}

	public void setrICMSInternoOrigemOrigin(float rICMSInternoOrigemOrigin) {
		this.rICMSInternoOrigemOrigin = rICMSInternoOrigemOrigin;
	}

	public float getrICMSInterEstadualOrigemOrigin() {
		return rICMSInterEstadualOrigemOrigin;
	}

	public void setrICMSInterEstadualOrigemOrigin(
			float rICMSInterEstadualOrigemOrigin) {
		this.rICMSInterEstadualOrigemOrigin = rICMSInterEstadualOrigemOrigin;
	}

	public float getrICMSEstadoOrigemInternoMaterialClassOrigin() {
		return rICMSEstadoOrigemInternoMaterialClassOrigin;
	}

	public void setrICMSEstadoOrigemInternoMaterialClassOrigin(
			float rICMSEstadoOrigemInternoMaterialClassOrigin) {
		this.rICMSEstadoOrigemInternoMaterialClassOrigin = rICMSEstadoOrigemInternoMaterialClassOrigin;
	}

	public float getrICMSEstadoDestinoDestination() {
		return rICMSEstadoDestinoDestination;
	}

	public void setrICMSEstadoDestinoDestination(float rICMSEstadoDestinoDestination) {
		this.rICMSEstadoDestinoDestination = rICMSEstadoDestinoDestination;
	}

	public float getrICMSMAterialClass() {
		return rICMSMAterialClass;
	}

	public void setrICMSMAterialClass(float rICMSMAterialClass) {
		this.rICMSMAterialClass = rICMSMAterialClass;
	}

	public float getrICMSInterEstadualDestination() {
		return rICMSInterEstadualDestination;
	}

	public void setrICMSInterEstadualDestination(float rICMSInterEstadualDestination) {
		this.rICMSInterEstadualDestination = rICMSInterEstadualDestination;
	}

	public float getrICMSInterEstadualMaterialImportadoDestination() {
		return rICMSInterEstadualMaterialImportadoDestination;
	}

	public void setrICMSInterEstadualMaterialImportadoDestination(
			float rICMSInterEstadualMaterialImportadoDestination) {
		this.rICMSInterEstadualMaterialImportadoDestination = rICMSInterEstadualMaterialImportadoDestination;
	}

	public float getrIVAMaterialClassDestination() {
		return rIVAMaterialClassDestination;
	}

	public void setrIVAMaterialClassDestination(float rIVAMaterialClassDestination) {
		this.rIVAMaterialClassDestination = rIVAMaterialClassDestination;
	}

	public float getrIVAMaterialImportadoMaterialClassDestination() {
		return rIVAMaterialImportadoMaterialClassDestination;
	}

	public void setrIVAMaterialImportadoMaterialClassDestination(
			float rIVAMaterialImportadoMaterialClassDestination) {
		this.rIVAMaterialImportadoMaterialClassDestination = rIVAMaterialImportadoMaterialClassDestination;
	}

	public float getrICMSInternoMaterialClassDestination() {
		return rICMSInternoMaterialClassDestination;
	}

	public void setrICMSInternoMaterialClassDestination(
			float rICMSInternoMaterialClassDestination) {
		this.rICMSInternoMaterialClassDestination = rICMSInternoMaterialClassDestination;
	}

	public float getrIPIMaterialClass() {
		return rIPIMaterialClass;
	}

	public void setrIPIMaterialClass(float rIPIMaterialClass) {
		this.rIPIMaterialClass = rIPIMaterialClass;
	}

	public float getrPISProductType() {
		return rPISProductType;
	}

	public void setrPISProductType(float rPISProductType) {
		this.rPISProductType = rPISProductType;
	}

	public float getrCOFINSProductType() {
		return rCOFINSProductType;
	}

	public void setrCOFINSProductType(float rCOFINSProductType) {
		this.rCOFINSProductType = rCOFINSProductType;
	}

	public float getrIRProductType() {
		return rIRProductType;
	}

	public void setrIRProductType(float rIRProductType) {
		this.rIRProductType = rIRProductType;
	}

	public float getrCSSLProductType() {
		return rCSSLProductType;
	}

	public void setrCSSLProductType(float rCSSLProductType) {
		this.rCSSLProductType = rCSSLProductType;
	}

	public float getrISSOrigin() {
		return rISSOrigin;
	}

	public void setrISSOrigin(float rISSOrigin) {
		this.rISSOrigin = rISSOrigin;
	}

	public float getrISSSoftOrigin() {
		return rISSSoftOrigin;
	}

	public void setrISSSoftOrigin(float rISSSoftOrigin) {
		this.rISSSoftOrigin = rISSSoftOrigin;
	}
	
	public float getrISSOriginServ() {
		return rISSOriginServ;
	}

	public void setrISSOriginServ(float rISSOriginServ) {
		this.rISSOriginServ = rISSOriginServ;
	}

	public float getrIVAOrigin() {
		return rIVAOrigin;
	}

	public void setrIVAOrigin(float rIVAOrigin) {
		this.rIVAOrigin = rIVAOrigin;
	}

	public float getrIVAMaterialImportadoOrigin() {
		return rIVAMaterialImportadoOrigin;
	}

	public void setrIVAMaterialImportadoOrigin(float rIVAMaterialImportadoOrigin) {
		this.rIVAMaterialImportadoOrigin = rIVAMaterialImportadoOrigin;
	}

	public float getrICMSEstadoOrigem() {
		return rICMSEstadoOrigem;
	}

	public void setrICMSEstadoOrigem(float rICMSEstadoOrigem) {
		this.rICMSEstadoOrigem = rICMSEstadoOrigem;
	}

	public float getrICMSEstadoOrigemInterno() {
		return rICMSEstadoOrigemInterno;
	}

	public void setrICMSEstadoOrigemInterno(float rICMSEstadoOrigemInterno) {
		this.rICMSEstadoOrigemInterno = rICMSEstadoOrigemInterno;
	}

	public float getrICMSEstadoDestino() {
		return rICMSEstadoDestino;
	}

	public void setrICMSEstadoDestino(float rICMSEstadoDestino) {
		this.rICMSEstadoDestino = rICMSEstadoDestino;
	}

	public float getrICMSMaterialClass() {
		return rICMSMaterialClass;
	}

	public void setrICMSMaterialClass(float rICMSMaterialClass) {
		this.rICMSMaterialClass = rICMSMaterialClass;
	}

	public float getrICMSInterEstadual() {
		return rICMSInterEstadual;
	}

	public void setrICMSInterEstadual(float rICMSInterEstadual) {
		this.rICMSInterEstadual = rICMSInterEstadual;
	}

	public float getrICMSInterEstadualMaterialImportado() {
		return rICMSInterEstadualMaterialImportado;
	}

	public void setrICMSInterEstadualMaterialImportado(
			float rICMSInterEstadualMaterialImportado) {
		this.rICMSInterEstadualMaterialImportado = rICMSInterEstadualMaterialImportado;
	}

	public float getrIVA() {
		return rIVA;
	}

	public void setrIVA(float rIVA) {
		this.rIVA = rIVA;
	}

	public float getrIVAMaterialImportado() {
		return rIVAMaterialImportado;
	}

	public void setrIVAMaterialImportado(float rIVAMaterialImportado) {
		this.rIVAMaterialImportado = rIVAMaterialImportado;
	}

	public float getrICMSInterno() {
		return rICMSInterno;
	}

	public void setrICMSInterno(float rICMSInterno) {
		this.rICMSInterno = rICMSInterno;
	}

	public float getrICMSRecuperar() {
		return rICMSRecuperar;
	}

	public void setrICMSRecuperar(float rICMSRecuperar) {
		this.rICMSRecuperar = rICMSRecuperar;
	}

	public float getrICMSARecuperarST() {
		return rICMSARecuperarST;
	}

	public void setrICMSARecuperarST(float rICMSARecuperarST) {
		this.rICMSARecuperarST = rICMSARecuperarST;
	}

	public float getrIPI() {
		return rIPI;
	}

	public void setrIPI(float rIPI) {
		this.rIPI = rIPI;
	}

	public float getrIPIRecuperar() {
		return rIPIRecuperar;
	}

	public void setrIPIRecuperar(float rIPIRecuperar) {
		this.rIPIRecuperar = rIPIRecuperar;
	}

	public float getrPIS() {
		return rPIS;
	}

	public void setrPIS(float rPIS) {
		this.rPIS = rPIS;
	}

	public float getrCOFINS() {
		return rCOFINS;
	}

	public void setrCOFINS(float rCOFINS) {
		this.rCOFINS = rCOFINS;
	}

	public float getrIR() {
		return rIR;
	}

	public void setrIR(float rIR) {
		this.rIR = rIR;
	}

	public float getrCSSL() {
		return rCSSL;
	}

	public void setrCSSL(float rCSSL) {
		this.rCSSL = rCSSL;
	}

	public float getrISS() {
		return rISS;
	}

	public void setrISS(float rISS) {
		this.rISS = rISS;
	}

	public double getmUnitICMSEstadoOrigem() {
		return mUnitICMSEstadoOrigem;
	}

	public void setmUnitICMSEstadoOrigem(double mUnitICMSEstadoOrigem) {
		this.mUnitICMSEstadoOrigem = mUnitICMSEstadoOrigem;
	}

	public double getmUnitICMSEstadoOrigemInterno() {
		return mUnitICMSEstadoOrigemInterno;
	}

	public void setmUnitICMSEstadoOrigemInterno(double mUnitICMSEstadoOrigemInterno) {
		this.mUnitICMSEstadoOrigemInterno = mUnitICMSEstadoOrigemInterno;
	}

	public double getmUnitICMSEstadoDestino() {
		return mUnitICMSEstadoDestino;
	}

	public void setmUnitICMSEstadoDestino(double mUnitICMSEstadoDestino) {
		this.mUnitICMSEstadoDestino = mUnitICMSEstadoDestino;
	}

	public double getmUnitICMSMaterialClass() {
		return mUnitICMSMaterialClass;
	}

	public void setmUnitICMSMaterialClass(double mUnitICMSMaterialClass) {
		this.mUnitICMSMaterialClass = mUnitICMSMaterialClass;
	}

	public double getmUnitICMSInterEstadual() {
		return mUnitICMSInterEstadual;
	}

	public void setmUnitICMSInterEstadual(double mUnitICMSInterEstadual) {
		this.mUnitICMSInterEstadual = mUnitICMSInterEstadual;
	}

	public double getmUnitICMSInterEstadualMaterialImportado() {
		return mUnitICMSInterEstadualMaterialImportado;
	}

	public void setmUnitICMSInterEstadualMaterialImportado(
			double mUnitICMSInterEstadualMaterialImportado) {
		this.mUnitICMSInterEstadualMaterialImportado = mUnitICMSInterEstadualMaterialImportado;
	}

	public double getmUnitICMSARecuperar() {
		return mUnitICMSARecuperar;
	}

	public void setmUnitICMSARecuperar(double mUnitICMSARecuperar) {
		this.mUnitICMSARecuperar = mUnitICMSARecuperar;
	}

	public double getmUnitICMSARecuperarST() {
		return mUnitICMSARecuperarST;
	}

	public void setmUnitICMSARecuperarST(double mUnitICMSARecuperarST) {
		this.mUnitICMSARecuperarST = mUnitICMSARecuperarST;
	}

	public double getmUnitICMSST() {
		return mUnitICMSST;
	}

	public void setmUnitICMSST(double mUnitICMSST) {
		this.mUnitICMSST = mUnitICMSST;
	}

	public double getmUnitIPI() {
		return mUnitIPI;
	}

	public void setmUnitIPI(double mUnitIPI) {
		this.mUnitIPI = mUnitIPI;
	}

	public double getmUnitIPIRecoverable() {
		return mUnitIPIRecoverable;
	}

	public void setmUnitIPIRecoverable(double mUnitIPIRecoverable) {
		this.mUnitIPIRecoverable = mUnitIPIRecoverable;
	}

	public double getmUnitPIS() {
		return mUnitPIS;
	}

	public void setmUnitPIS(double mUnitPIS) {
		this.mUnitPIS = mUnitPIS;
	}

	public double getmUnitCofins() {
		return mUnitCofins;
	}

	public void setmUnitCofins(double mUnitCofins) {
		this.mUnitCofins = mUnitCofins;
	}

	public double getmUnitIR() {
		return mUnitIR;
	}

	public void setmUnitIR(double mUnitIR) {
		this.mUnitIR = mUnitIR;
	}

	public double getmUnitCSSL() {
		return mUnitCSSL;
	}

	public void setmUnitCSSL(double mUnitCSSL) {
		this.mUnitCSSL = mUnitCSSL;
	}

	public double getmUnitISS() {
		return mUnitISS;
	}

	public void setmUnitISS(double mUnitISS) {
		this.mUnitISS = mUnitISS;
	}

	public double getmICMSEstadoOrigem() {
		return mICMSEstadoOrigem;
	}

	public void setmICMSEstadoOrigem(double mICMSEstadoOrigem) {
		this.mICMSEstadoOrigem = mICMSEstadoOrigem;
	}

	public double getmICMSEstadoOrigemInterno() {
		return mICMSEstadoOrigemInterno;
	}

	public void setmICMSEstadoOrigemInterno(double mICMSEstadoOrigemInterno) {
		this.mICMSEstadoOrigemInterno = mICMSEstadoOrigemInterno;
	}

	public double getmICMSEstadoDestino() {
		return mICMSEstadoDestino;
	}

	public void setmICMSEstadoDestino(double mICMSEstadoDestino) {
		this.mICMSEstadoDestino = mICMSEstadoDestino;
	}

	public double getmICMSMaterialClass() {
		return mICMSMaterialClass;
	}

	public void setmICMSMaterialClass(double mICMSMaterialClass) {
		this.mICMSMaterialClass = mICMSMaterialClass;
	}

	public double getmICMSInterEstadual() {
		return mICMSInterEstadual;
	}

	public void setmICMSInterEstadual(double mICMSInterEstadual) {
		this.mICMSInterEstadual = mICMSInterEstadual;
	}

	public double getmICMSInterEstadualMaterialImportado() {
		return mICMSInterEstadualMaterialImportado;
	}

	public void setmICMSInterEstadualMaterialImportado(
			double mICMSInterEstadualMaterialImportado) {
		this.mICMSInterEstadualMaterialImportado = mICMSInterEstadualMaterialImportado;
	}

	public double getmICMSARecuperar() {
		return mICMSARecuperar;
	}

	public void setmICMSARecuperar(double mICMSARecuperar) {
		this.mICMSARecuperar = mICMSARecuperar;
	}

	public double getmICMSARecuperarST() {
		return mICMSARecuperarST;
	}

	public void setmICMSARecuperarST(double mICMSARecuperarST) {
		this.mICMSARecuperarST = mICMSARecuperarST;
	}

	public double getmICMSST() {
		return mICMSST;
	}

	public void setmICMSST(double mICMSST) {
		this.mICMSST = mICMSST;
	}

	public double getmIPI() {
		return mIPI;
	}

	public void setmIPI(double mIPI) {
		this.mIPI = mIPI;
	}

	public double getmIPIReceber() {
		return mIPIReceber;
	}

	public void setmIPIReceber(double mIPIReceber) {
		this.mIPIReceber = mIPIReceber;
	}

	public double getmPIS() {
		return mPIS;
	}

	public void setmPIS(double mPIS) {
		this.mPIS = mPIS;
	}

	public double getmCOFINS() {
		return mCOFINS;
	}

	public void setmCOFINS(double mCOFINS) {
		this.mCOFINS = mCOFINS;
	}

	public double getmIR() {
		return mIR;
	}

	public void setmIR(double mIR) {
		this.mIR = mIR;
	}

	public double getmCSSL() {
		return mCSSL;
	}

	public void setmCSSL(double mCSSL) {
		this.mCSSL = mCSSL;
	}

	public double getmISS() {
		return mISS;
	}

	public void setmISS(double mISS) {
		this.mISS = mISS;
	}

	public double getmTaxesRecoverableMargin() {
		return mTaxesRecoverableMargin;
	}

	public void setmTaxesRecoverableMargin(double mTaxesRecoverableMargin) {
		this.mTaxesRecoverableMargin = mTaxesRecoverableMargin;
	}

	public float getrMarginItem() {
		return rMarginItem;
	}

	public void setrMarginItem(float rMarginItem) {
		this.rMarginItem = rMarginItem;
	}

	public double getmTotalTaxes() {
		return mTotalTaxes;
	}

	public void setmTotalTaxes(double mTotalTaxes) {
		this.mTotalTaxes = mTotalTaxes;
	}

	public double getmUnitGrossPrice() {
		return mUnitGrossPrice;
	}

	public void setmUnitGrossPrice(double mUnitGrossPrice) {
		this.mUnitGrossPrice = mUnitGrossPrice;
	}

	public double getmGrossPrice() {
		return mGrossPrice;
	}

	public void setmGrossPrice(double mGrossPrice) {
		this.mGrossPrice = mGrossPrice;
	}

	public int getiCalculationModel() {
		return iCalculationModel;
	}

	public void setiCalculationModel(int iCalculationModel) {
		this.iCalculationModel = iCalculationModel;
	}

	public String getsCalculationMemoryMaterial() {
		return sCalculationMemoryMaterial;
	}

	public void setsCalculationMemoryMaterial(String sCalculationMemoryMaterial) {
		this.sCalculationMemoryMaterial = sCalculationMemoryMaterial;
	}

	public String getsDescriptionMaterial() {
		return sDescriptionMaterial;
	}

	public void setsDescriptionMaterial(String sDescriptionMaterial) {
		this.sDescriptionMaterial = sDescriptionMaterial;
	}

	public String getsCommentsOtherCost() {
		return sCommentsOtherCost;
	}

	public void setsCommentsOtherCost(String sCommentsOtherCost) {
		this.sCommentsOtherCost = sCommentsOtherCost;
	}

	public float getrICMSMaterialClassMaterialClass() {
		return rICMSMaterialClassMaterialClass;
	}

	public void setrICMSMaterialClassMaterialClass(
			float rICMSMaterialClassMaterialClass) {
		this.rICMSMaterialClassMaterialClass = rICMSMaterialClassMaterialClass;
	}

	public float getrICMSProprioARecuperar() {
		return rICMSProprioARecuperar;
	}

	public void setrICMSProprioARecuperar(float rICMSProprioARecuperar) {
		this.rICMSProprioARecuperar = rICMSProprioARecuperar;
	}

	public double getmUnitICMSProprioARecuperar() {
		return mUnitICMSProprioARecuperar;
	}

	public void setmUnitICMSProprioARecuperar(double mUnitICMSProprioARecuperar) {
		this.mUnitICMSProprioARecuperar = mUnitICMSProprioARecuperar;
	}

	public double getmICMSProprioARecuperar() {
		return mICMSProprioARecuperar;
	}

	public void setmICMSProprioARecuperar(double mICMSProprioARecuperar) {
		this.mICMSProprioARecuperar = mICMSProprioARecuperar;
	}

	public double getmBaseCalculoST() {
		return mBaseCalculoST;
	}

	public void setmBaseCalculoST(double mBaseCalculoST) {
		this.mBaseCalculoST = mBaseCalculoST;
	}

	public double getrGrossMargin() {
		return rGrossMargin;
	}

	public void setrGrossMargin(double rGrossMargin) {
		this.rGrossMargin = rGrossMargin;
	}

	public String getsOrdem() {
		return sOrdem;
	}

	public void setsOrdem(String sOrdem) {
		this.sOrdem = sOrdem;
	}

	public void setStyle(String style) {
		this.style = style;
	}
	
	public String getStyle() {
		
		if((idAdmMaterialClass == 0 && (sNCM == null || sNCM.isEmpty())) ){//|| (fAvailableMaterialClass == 0)){
			style = "color: #FF0000;";
		}else {
			style = "";			
		}		
		
		return style;
	}

	public boolean isChecked() {
		return checked;
	}

	public void setChecked(boolean checked) {
		this.checked = checked;
	}

	public float getNetMargin() {
		return netMargin;
	}

	public void setNetMargin(float netMargin) {
		this.netMargin = netMargin;
	}

	public int getfVariacaoPartNumber() {
		return fVariacaoPartNumber;
	}

	public void setfVariacaoPartNumber(int fVariacaoPartNumber) {
		this.fVariacaoPartNumber = fVariacaoPartNumber;
	}

	public List<SomaTotaisTO> getListaTotais() {
		return listaTotais;
	}

	public void setListaTotais(List<SomaTotaisTO> listaTotais) {
		this.listaTotais = listaTotais;
	}

	public int getfAvailableMaterial() {
		return fAvailableMaterial;
	}

	public void setfAvailableMaterial(int fAvailableMaterial) {
		this.fAvailableMaterial = fAvailableMaterial;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getStyleTd() {
		
		if(id == idTaxQuoteItem){
			styleTd = "font-weight: bold; background: #BDE1E2;";
		}else if((id != idTaxQuoteItem) && (idTaxQuoteItem != 0) && ( id % 2 == 0)){ 
			styleTd = "background: #EEFFFC;";
		}else if((id != idTaxQuoteItem) && (idTaxQuoteItem != 0) && ( id % 2 == 1)){
			styleTd = "background: #F7FFFC;";
		}else if(( id % 2 == 0)){
			styleTd = "background: #EAE8E8;";
		}else{
			styleTd = "";
		}
		
		return styleTd;
	}

	public void setStyleTd(String styleTd) {
		this.styleTd = styleTd;
	}
	
	public String getStyleTdNcm(){
				
		if(idAdmMaterialClassOriginal != 0){
			return "background: #F7F6C4 !important;";
		}else if(id == idTaxQuoteItem){
			return "font-weight: bold; background: #BDE1E2;";
		}else if((id != idTaxQuoteItem) && (idTaxQuoteItem != 0) && ( id % 2 == 0)){ 
			return "background: #EEFFFC;";
		}else if((id != idTaxQuoteItem) && (idTaxQuoteItem != 0) && ( id % 2 == 1)){
			return "background: #F7FFFC;";
		}else if(( id % 2 == 0)){
			return "background: #EAE8E8;";
		}else{
			return "";
		}		
		
	}
	
	public long getIdTaxQuoteItemOriginal() {
		return idTaxQuoteItemOriginal;
	}

	public void setIdTaxQuoteItemOriginal(long idTaxQuoteItemOriginal) {
		this.idTaxQuoteItemOriginal = idTaxQuoteItemOriginal;
	}

	public int getfItemPaiManual() {
		return fItemPaiManual;
	}

	public void setfItemPaiManual(int fItemPaiManual) {
		this.fItemPaiManual = fItemPaiManual;
	}

	public long getIdAdmMaterialClassOriginal() {
		return idAdmMaterialClassOriginal;
	}

	public void setIdAdmMaterialClassOriginal(long idAdmMaterialClassOriginal) {
		this.idAdmMaterialClassOriginal = idAdmMaterialClassOriginal;
	}

	public String getsNCMOriginal() {
		return sNCMOriginal;
	}

	public void setsNCMOriginal(String sNCMOriginal) {
		this.sNCMOriginal = sNCMOriginal;
	}

	public int getfUseMaxIvaMaterialImportado() {
		return fUseMaxIvaMaterialImportado;
	}

	public void setfUseMaxIvaMaterialImportado(int fUseMaxIvaMaterialImportado) {
		this.fUseMaxIvaMaterialImportado = fUseMaxIvaMaterialImportado;
	}

	public int getfAutoGeneratedBySystem() {
		return fAutoGeneratedBySystem;
	}

	public void setfAutoGeneratedBySystem(int fAutoGeneratedBySystem) {
		this.fAutoGeneratedBySystem = fAutoGeneratedBySystem;
	}

	
	
}
